version: '3.5'
services:
  backup:
    #restart: unless-stopped
    build:
      context: .
    #user: "1000"
    volumes:
      - ./:/directory1:ro
      - ./:/directory2:ro
      - ./:/directory3:ro
    env_file:
      - .env
    #environment:
        # "Schedule" keys can be cron or times (2h, 4d, 1w), and multiples values separated by ";"

        # REPOSITORY_OVH-GRA_LOCATION=swift:xx:/
        # REPOSITORY_OVH-GRA_PASSWORD=abc
        # REPOSITORY_OVH-GRA_OS_AUTH_URL=https://auth.cloud.ovh.net/v3
        # REPOSITORY_OVH-GRA_OS_PROJECT_ID=xx
        # REPOSITORY_OVH-GRA_OS_PROJECT_NAME="xx"
        # REPOSITORY_OVH-GRA_OS_REGION_NAME="GRA"
        # REPOSITORY_OVH-GRA_OS_USER_DOMAIN_NAME="Default"
        # REPOSITORY_OVH-GRA_OS_PROJECT_DOMAIN_ID="default"
        # REPOSITORY_OVH-GRA_OS_USERNAME="user-xx"
        # REPOSITORY_OVH-GRA_OS_PASSWORD="xx"
        # REPOSITORY_OVH-GRA_OS_IDENTITY_API_VERSION=3
        # REPOSITORY_OVH-GRA_CHECK_SCHEDULE=1d

        # REPOSITORY_USB-DD_LOCATION=/media/USB-DD/backups/
        # REPOSITORY_USB-DD_PASSWORD=cab

        # BACKUP_APP1_REPOSITORIES=OVH-GRA,USB-DD
        # BACKUP_APP1_HOSTNAME=rpi01
        # BACKUP_APP1_PATHS=/directory1,/directory2
        # BACKUP_APP1_EXCLUDES=.git,.sync
        # BACKUP_APP1_SCHEDULE=* */6 * * *

        # BACKUP_APP2_REPOSITORIES=USB-DD
        # BACKUP_APP2_PATHS=/directory3
        # BACKUP_APP2_SCHEDULE=12h

        # UPLOADLIMIT=50K
        # DOWNLOADLIMIT=200K

        # LOG_LEVEL=info

