version: '3.5'
services:
  backup:
    #restart: unless-stopped
    build:
      context: .
    #user: "1000"
    hostname: "my-computer"
    volumes:
      - ./:/directory:ro
    env_file:
      - .env
    environment:
      # - RESTIC_PASSWORD=xxxxxxxxxxxxxxxxxxx
      # - RESTIC_REPOSITORY=swift:xxxxxxxxxxx:/
      # - RESTIC_REPOSITORY=/tmp/test
      # - OS_AUTH_URL=https://auth.cloud.ovh.net/v3
      # - OS_PROJECT_ID=xxxxxxxxxxxx
      # - OS_PROJECT_NAME=xxxxxxxxxxxx
      # - OS_REGION_NAME=GRA
      # - OS_USER_DOMAIN_NAME=Default
      # - OS_PROJECT_DOMAIN_ID=default
      # - OS_USERNAME=user-xxxxxxxxx
      # - OS_PASSWORD=xxxxx
      # - OS_IDENTITY_API_VERSION=3
      - BACKUP_MAIN_PATHS=/directory
      - BACKUP_MAIN_EXCLUDES=.git,.sync
      - BACKUP_MAIN_FREQUENCY=1m
      - CHECK_FREQUENCY=2m
      - GLOBAL_UPLOAD_LIMIT=50K
      - GLOBAL_DOWNLOAD_LIMIT=200K
