version: '3.5'
services:
  backup:
    #restart: unless-stopped
    build:
      context: .
    #user: "1000"
    volumes:
      - ./:/directory:ro
    env_file:
      - .env
    # environment:
    #   REPOSITORY_OVH-GRA_LOCATION=swift:poopidou2:/
    #   REPOSITORY_OVH-GRA_PASSWORD=abc
    #   REPOSITORY_OVH-GRA_OS_AUTH_URL=https://auth.cloud.ovh.net/v3
    #   REPOSITORY_OVH-GRA_OS_PROJECT_ID=xxx
    #   REPOSITORY_OVH-GRA_OS_PROJECT_NAME="xxx"
    #   REPOSITORY_OVH-GRA_OS_REGION_NAME="GRA"
    #   REPOSITORY_OVH-GRA_OS_USER_DOMAIN_NAME="Default"
    #   REPOSITORY_OVH-GRA_OS_PROJECT_DOMAIN_ID="default"
    #   REPOSITORY_OVH-GRA_OS_USERNAME="user-xxx"
    #   REPOSITORY_OVH-GRA_OS_PASSWORD="xxx"
    #   REPOSITORY_OVH-GRA_OS_IDENTITY_API_VERSION=3
    #   REPOSITORY_OVH-GRA_CHECK_CHECK_SCHEDULE=2d

    #   REPOSITORY_AWS-IRL_LOCATION=aws:cotcot:/
    #   REPOSITORY_AWS-IRL_PASSWORD=bac
    #   REPOSITORY_AWS-IRL_AWS_ACCESS_KEY_ID=xxx

    #   REPOSITORY_USB-DD_LOCATION=/media/USB-DD/backups/
    #   REPOSITORY_USB-DD_PASSWORD=cab

    #   BACKUP_APP1_REPOSITORIES=OVH-GRA,USB-DD
    #   BACKUP_APP1_HOSTNAME=rpi01
    #   BACKUP_APP1_PATHS=/directory1,/directory2
    #   BACKUP_APP1_EXCLUDES=.git,.sync
    #   BACKUP_APP1_SCHEDULE=*/5 * * * *;2h

    #   BACKUP_APP1_REPOSITORIES=AWS-IRL,USB-DD
    #   BACKUP_APP1_PATHS=/directory3
    #   BACKUP_APP1_SCHEDULE=24h

    #   UPLOADLIMIT=50K
    #   DOWNLOADLIMIT=200K
